on:
  workflow_dispatch:
#  push:

name: Run SST anomaly calculations

jobs:
  build1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install command line packages
        run: |
          sudo apt update
          sudo apt-get install  libgdal-dev libcurl4-gnutls-dev libgit2-dev libudunits2-dev libharfbuzz-dev libfribidi-dev
        shell: bash

      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.0.3' # problem with using 4.0.4

      - name: Cache R packages
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ecopull-cache2

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e '
          install.packages(c("ncdf4", "knitr", "usethis", "raster", "rgdal",
          "here", "devtools", "dplyr", "sf", "ggplot2", "reshape2", "stringr"))
          devtools::install_github("NOAA-EDAB/ecodata")'

      - name: Mask satellite data and save
        run: |
          Rscript -e '
          try(source(here::here("data-raw", "get_epu_sst_seasonal_anom.R")))
          try(source(here::here("data-raw", "get_esp_sst_seasonal_anom.R")))'

      - name: Check directory size
        run: |
          cd data-raw
          du -s
        shell: bash

      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: data # The folder the action should deploy.
          target-folder: data
          clean: false # Automatically remove deleted files from the deploy branch
