on:
  workflow_dispatch:
  push:

name: Test .nc from API

jobs:
  build1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install command line packages
        run: |
          sudo apt update
          sudo apt-get install  libgdal-dev libcurl4-gnutls-dev libgit2-dev libudunits2-dev libharfbuzz-dev libfribidi-dev
        shell: bash

      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.0.3' # problem with using 4.0.4

      - name: Cache R packages
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ecopull-cache

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("ncdf4", "knitr", "usethis", "raster", "here"))'

      - name: Test
        run: |
          Rscript -e '
          url <- "https://downloads.psl.noaa.gov/Datasets/noaa.oisst.v2.highres/icec.day.mean.2021.v2.nc"
          download.file(url, "test.nc", timeout = 600)

          internet_ltm <- ncdf4::nc_open("test.nc")
          usethis::use_data(internet_ltm, overwrite = TRUE)

          years <- 2017:2021

          for(i in years) {
            name <- paste0(i, ".nc")
            url <- paste0("https://downloads.psl.noaa.gov/Datasets/noaa.oisst.v2.highres/sst.day.mean.", i, ".v2.nc")
            download.file(url, destfile = name, timeout = 600)

            text <- knitr::knit_expand(text = readLines(here::here("inst/create_temps.R")),
                                       year = i)

            print(text)
            try(eval(parse(text = text)))
            print(paste("finished", i))

          }'

      - name: Check directory size
        run: |
          cd data
          du -s
        shell: bash

      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: data # The folder the action should deploy.
          target-folder: data
          clean: false # Automatically remove deleted files from the deploy branch
